In [27]:
import pandas as pd

In [28]:
df = pd.read_csv("data/registro_partida.csv")
df.groupby(['ModeloA', 'ModeloB','Profundidade']).mean()

                                                      Estados Visitados  \
ModeloA             ModeloB             Profundidade
Alpha-Beta          Iterative Deepening 2                     28.875000
                                        3                    165.333333
                                        4                    280.000000
                                        5                   2847.562500
                    MinMax              2                     28.875000
                                        3                    165.333333
                                        4                    280.000000
                                        5                   2847.562500
Iterative Deepening Alpha-Beta          2                     36.428571
                                        3                    204.200000
                                        4                    387.842105
                                        5                   3423.750000
MinMax              Alpha-Beta          2                     47.000000
                                        3                    327.600000
                                        4                   1008.894737
                                        5                  11350.875000
                    Random              2                     56.363636
                                        3                    386.538462
                                        4                   2535.764706
                                        5                  15391.000000

                                                      Tempo por Jogada
ModeloA             ModeloB             Profundidade
Alpha-Beta          Iterative Deepening 2                     0.000583
                                        3                     0.002837
                                        4                     0.005330
                                        5                     0.059359
                    MinMax              2                     0.000706
                                        3                     0.002650
                                        4                     0.005181
                                        5                     0.058883
Iterative Deepening Alpha-Beta          2                     0.000867
                                        3                     0.003337
                                        4                     0.008564
                                        5                     0.071666
MinMax              Alpha-Beta          2                     0.000860
                                        3                     0.005900
                                        4                     0.021325
                                        5                     0.225732
                    Random              2                     0.000941
                                        3                     0.007395
                                        4                     0.047703
                                        5                     0.292026

In [29]:
df = pd.read_csv("data/registro_partida_1.csv")
df.groupby(['ModeloA', 'ModeloB','Profundidade']).mean()

                                                      Estados Visitados  \
ModeloA             ModeloB             Profundidade
Alpha-Beta          Iterative Deepening 2                     28.875000
                                        3                    165.333333
                                        4                    280.000000
                                        5                   2847.562500
Iterative Deepening Alpha-Beta          2                     36.428571
                                        3                    204.200000
                                        4                    387.842105
                                        5                   3423.750000

                                                      Tempo por Jogada
ModeloA             ModeloB             Profundidade
Alpha-Beta          Iterative Deepening 2                     0.000549
                                        3                     0.002878
                                        4                     0.005500
                                        5                     0.061100
Iterative Deepening Alpha-Beta          2                     0.000700
                                        3                     0.003906
                                        4                     0.007224
                                        5                     0.074513